version: "3.3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
    - /home/mysql/data:/var/lib/mysql
  spring_boot_project:
    image: azizallouche/achat
    container_name: achat
    restart: on-failure
    ports:
      - 9090:9090
    depends_on:
      - mysqldb
  achatfront:
    image: azizallouche/achatfront
    container_name: achatfront
    expose:
      - 4200
    links:
      - spring_boot_project
    depends_on:
      - spring_boot_project
    ports:
      - 4200:4200
    restart: on-failure
    command: "ng serve --open --host 192.168.1.9 --port 4200 --disable-host-check"