version: "3.3"

services:

  mysqldb_standalone:
  
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
    
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achat
      
    ports:
      - "3306:3306"

  spring_boot_project:
  
    image: achat
    container_name: achat
    restart: on-failure
    build:
        context: ./
        dockerfile: Dockerfile
    ports:
      - 9050:9050
    depends_on:
      - mysqldb