version: "3"
services:
 mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:

      - MYSQL_DATABASE=achatdb
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    image: yosrjrah/achat
    container_name: projetachat
    restart: on-failure
    ports:
      - "8089:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/achatdb?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    db:
  

